// ============================================================
// Fallback demo data when TMDB API is unavailable
// ============================================================
import type { Movie, Genre } from "@/types";

export const DEMO_GENRES: Genre[] = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 10770, name: "TV Movie" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];

export const DEMO_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Interstellar",
    original_title: "Interstellar",
    overview:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival. When Earth becomes uninhabitable, former NASA pilot Cooper joins a desperate mission across the cosmos.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.6,
    vote_count: 30000,
    release_date: "2014-11-05",
    genre_ids: [18, 878, 12],
    popularity: 140.5,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 169,
  },
  {
    id: 2,
    title: "The Dark Knight",
    original_title: "The Dark Knight",
    overview:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 9.0,
    vote_count: 32000,
    release_date: "2008-07-14",
    genre_ids: [28, 80, 18],
    popularity: 130.2,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 152,
  },
  {
    id: 3,
    title: "Inception",
    original_title: "Inception",
    overview:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.8,
    vote_count: 35000,
    release_date: "2010-07-16",
    genre_ids: [28, 878, 12],
    popularity: 125.0,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 148,
  },
  {
    id: 4,
    title: "Dune: Part Two",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.4,
    vote_count: 9200,
    release_date: "2024-03-01",
    genre_ids: [878, 12],
    popularity: 220.8,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 166,
  },
  {
    id: 5,
    title: "Oppenheimer",
    original_title: "Oppenheimer",
    overview:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.3,
    vote_count: 20000,
    release_date: "2023-07-21",
    genre_ids: [18, 36],
    popularity: 190.0,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 180,
  },
  {
    id: 6,
    title: "The Shawshank Redemption",
    original_title: "The Shawshank Redemption",
    overview:
      "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic human decency.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.7,
    vote_count: 25000,
    release_date: "1994-09-23",
    genre_ids: [18],
    popularity: 90.5,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 142,
  },
  {
    id: 7,
    title: "Parasite",
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes a wealthy family's house over as they begin to systematically infiltrate their household and start living their dreams.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.5,
    vote_count: 17000,
    release_date: "2019-05-30",
    genre_ids: [35, 18, 53],
    popularity: 95.3,
    original_language: "ko",
    adult: false,
    video: false,
    runtime: 132,
  },
  {
    id: 8,
    title: "Gladiator II",
    original_title: "Gladiator II",
    overview:
      "After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum and must look to his past to find strength to return the glory of Rome to its people.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.1,
    vote_count: 4000,
    release_date: "2024-11-22",
    genre_ids: [28, 12, 18],
    popularity: 200.0,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 148,
  },
  {
    id: 9,
    title: "Poor Things",
    original_title: "Poor Things",
    overview:
      "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.0,
    vote_count: 11000,
    release_date: "2023-12-08",
    genre_ids: [18, 35, 14],
    popularity: 105.2,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 141,
  },
  {
    id: 10,
    title: "Inside Out 2",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is suddenly turned upside down when Joy, Sadness, Anger, Fear and Disgust who've long been running a successful operation, are forced to make room for a whole new roster of emotions.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.8,
    vote_count: 8500,
    release_date: "2024-06-14",
    genre_ids: [16, 10751, 12],
    popularity: 185.0,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 100,
  },
  {
    id: 11,
    title: "Furiosa: A Mad Max Saga",
    original_title: "Furiosa: A Mad Max Saga",
    overview:
      "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great biker horde led by the warlord Dementus.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.6,
    vote_count: 6000,
    release_date: "2024-05-24",
    genre_ids: [28, 12],
    popularity: 160.0,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 148,
  },
  {
    id: 12,
    title: "The Substance",
    original_title: "The Substance",
    overview:
      "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 7.3,
    vote_count: 4500,
    release_date: "2024-09-20",
    genre_ids: [27, 878],
    popularity: 145.0,
    original_language: "en",
    adult: false,
    video: false,
    runtime: 141,
  },
];
